spring.application.name=techforum

spring.datasource.url=jdbc:mysql://localhost:3306/databasename
spring.datasource.username=databaseusername
spring.datasource.password=databasepassword

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET}
